schema_version = "1.0.0"
id = "blendmate"
version = "0.1.0"
blender_version_min = "4.0.0"
name = "Blendmate Connector"
tagline = "Connect Blender to Blendmate app"
maintainer = "Jiri Lebduska"
type = "add-on"
permissions = ["network"]
license = ["MIT"]

website = "https://github.com/lebduska/blendmate"
